name: gh-pages CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
    - name: Setup git credentials
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    - run: |
        git config --global user.name 'gh-pages CI'
        git config --global user.email 'numanaral@users.noreply.github.com'
    - name: Setup node and deploy to gh-pages
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run deploy
      env:
        CI: true
